# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcello/Documenti/sacks/sacksSvnUser/interface/web/web.ui'
#
# Created: Sat Mar  6 13:08:22 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_webForm(object):
    def setupUi(self, webForm):
        webForm.setObjectName("webForm")
        webForm.resize(509, 381)
        webForm.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(webForm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.urlWeb = QtGui.QLineEdit(self.centralwidget)
        self.urlWeb.setMinimumSize(QtCore.QSize(0, 0))
        self.urlWeb.setObjectName("urlWeb")
        self.gridLayout.addWidget(self.urlWeb, 0, 0, 1, 1)
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 1, 0, 1, 2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 1, 1, 1)
        webForm.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(webForm)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 509, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuWeb = QtGui.QMenu(self.menuBar)
        self.menuWeb.setObjectName("menuWeb")
        webForm.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(webForm)
        self.toolBar.setObjectName("toolBar")
        webForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(webForm)
        self.statusBar.setObjectName("statusBar")
        webForm.setStatusBar(self.statusBar)
        self.actionBack = QtGui.QAction(webForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/web/images/actions/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon)
        self.actionBack.setObjectName("actionBack")
        self.actionNext = QtGui.QAction(webForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/web/images/actions/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon1)
        self.actionNext.setObjectName("actionNext")
        self.actionReload = QtGui.QAction(webForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/web/images/actions/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon2)
        self.actionReload.setObjectName("actionReload")
        self.actionStop = QtGui.QAction(webForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/web/images/actions/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionPrint = QtGui.QAction(webForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/web/images/actions/fileprint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrintPreview = QtGui.QAction(webForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/web/images/actions/filefind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintPreview.setIcon(icon5)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionSpreadLink = QtGui.QAction(webForm)
        self.actionSpreadLink.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/web/images/actions/bookmark_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpreadLink.setIcon(icon6)
        self.actionSpreadLink.setObjectName("actionSpreadLink")
        self.menuWeb.addAction(self.actionBack)
        self.menuWeb.addAction(self.actionNext)
        self.menuWeb.addAction(self.actionReload)
        self.menuWeb.addAction(self.actionStop)
        self.menuWeb.addSeparator()
        self.menuWeb.addAction(self.actionPrint)
        self.menuWeb.addAction(self.actionPrintPreview)
        self.menuBar.addAction(self.menuWeb.menuAction())
        self.toolBar.addAction(self.actionBack)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionPrintPreview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSpreadLink)

        self.retranslateUi(webForm)
        QtCore.QObject.connect(self.webView, QtCore.SIGNAL("loadProgress(int)"), self.progressBar.setValue)
        QtCore.QObject.connect(self.webView, QtCore.SIGNAL("titleChanged(QString)"), self.statusBar.showMessage)
        QtCore.QMetaObject.connectSlotsByName(webForm)

    def retranslateUi(self, webForm):
        webForm.setWindowTitle(QtGui.QApplication.translate("webForm", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWeb.setTitle(QtGui.QApplication.translate("webForm", "Web", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("webForm", "Web ToolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBack.setText(QtGui.QApplication.translate("webForm", "back", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("webForm", "next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setText(QtGui.QApplication.translate("webForm", "reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setShortcut(QtGui.QApplication.translate("webForm", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("webForm", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("webForm", "print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPreview.setText(QtGui.QApplication.translate("webForm", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPreview.setToolTip(QtGui.QApplication.translate("webForm", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpreadLink.setText(QtGui.QApplication.translate("webForm", "spreadLink", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    webForm = QtGui.QMainWindow()
    ui = Ui_webForm()
    ui.setupUi(webForm)
    webForm.show()
    sys.exit(app.exec_())

