# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcello/Documenti/sacks/sacksSvnUser/stream/streamWidget.ui'
#
# Created: Sat Mar  6 13:07:51 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_streamWidget(object):
    def setupUi(self, streamWidget):
        streamWidget.setObjectName("streamWidget")
        streamWidget.resize(249, 357)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stream/interface/images/apps/package_multimedia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        streamWidget.setWindowIcon(icon)
        self.gridLayout_3 = QtGui.QGridLayout(streamWidget)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(streamWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBoxVideoBitrate = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxVideoBitrate.setObjectName("checkBoxVideoBitrate")
        self.horizontalLayout_4.addWidget(self.checkBoxVideoBitrate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.spinBoxVideoBitrate = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxVideoBitrate.setEnabled(False)
        self.spinBoxVideoBitrate.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBoxVideoBitrate.setWrapping(False)
        self.spinBoxVideoBitrate.setAccelerated(True)
        self.spinBoxVideoBitrate.setMaximum(2056)
        self.spinBoxVideoBitrate.setObjectName("spinBoxVideoBitrate")
        self.horizontalLayout_4.addWidget(self.spinBoxVideoBitrate)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxAudioBitrate = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxAudioBitrate.setObjectName("checkBoxAudioBitrate")
        self.horizontalLayout_5.addWidget(self.checkBoxAudioBitrate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.spinBoxAudioBitrate = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxAudioBitrate.setEnabled(False)
        self.spinBoxAudioBitrate.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBoxAudioBitrate.setAccelerated(True)
        self.spinBoxAudioBitrate.setMaximum(256)
        self.spinBoxAudioBitrate.setObjectName("spinBoxAudioBitrate")
        self.horizontalLayout_5.addWidget(self.spinBoxAudioBitrate)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(streamWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBoxAcquisition = QtGui.QGroupBox(streamWidget)
        self.groupBoxAcquisition.setObjectName("groupBoxAcquisition")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxAcquisition)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayoutV4lType = QtGui.QHBoxLayout()
        self.horizontalLayoutV4lType.setObjectName("horizontalLayoutV4lType")
        self.label = QtGui.QLabel(self.groupBoxAcquisition)
        self.label.setObjectName("label")
        self.horizontalLayoutV4lType.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutV4lType.addItem(spacerItem2)
        self.comboBoxV4l = QtGui.QComboBox(self.groupBoxAcquisition)
        self.comboBoxV4l.setObjectName("comboBoxV4l")
        self.comboBoxV4l.addItem(QtCore.QString())
        self.comboBoxV4l.addItem(QtCore.QString())
        self.horizontalLayoutV4lType.addWidget(self.comboBoxV4l)
        self.gridLayout_2.addLayout(self.horizontalLayoutV4lType, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBoxAcquisition)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lineEditDevVideo = QtGui.QLineEdit(self.groupBoxAcquisition)
        self.lineEditDevVideo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditDevVideo.setObjectName("lineEditDevVideo")
        self.horizontalLayout_2.addWidget(self.lineEditDevVideo)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBoxAcquisition)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lineEditDevAudio = QtGui.QLineEdit(self.groupBoxAcquisition)
        self.lineEditDevAudio.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditDevAudio.setObjectName("lineEditDevAudio")
        self.horizontalLayout_3.addWidget(self.lineEditDevAudio)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBoxAudioSamplerate = QtGui.QCheckBox(self.groupBoxAcquisition)
        self.checkBoxAudioSamplerate.setChecked(False)
        self.checkBoxAudioSamplerate.setObjectName("checkBoxAudioSamplerate")
        self.horizontalLayout_7.addWidget(self.checkBoxAudioSamplerate)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.spinBoxAudioSamplerate = QtGui.QSpinBox(self.groupBoxAcquisition)
        self.spinBoxAudioSamplerate.setEnabled(False)
        self.spinBoxAudioSamplerate.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBoxAudioSamplerate.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxAudioSamplerate.setWrapping(False)
        self.spinBoxAudioSamplerate.setFrame(True)
        self.spinBoxAudioSamplerate.setAccelerated(True)
        self.spinBoxAudioSamplerate.setProperty("value", QtCore.QVariant(0))
        self.spinBoxAudioSamplerate.setObjectName("spinBoxAudioSamplerate")
        self.horizontalLayout_7.addWidget(self.spinBoxAudioSamplerate)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.groupBoxAcquisition)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.comboBoxInputNum = QtGui.QComboBox(self.groupBoxAcquisition)
        self.comboBoxInputNum.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBoxInputNum.setObjectName("comboBoxInputNum")
        self.comboBoxInputNum.addItem(QtCore.QString())
        self.comboBoxInputNum.setItemText(0, "")
        self.comboBoxInputNum.addItem(QtCore.QString())
        self.comboBoxInputNum.addItem(QtCore.QString())
        self.comboBoxInputNum.addItem(QtCore.QString())
        self.comboBoxInputNum.addItem(QtCore.QString())
        self.horizontalLayout_6.addWidget(self.comboBoxInputNum)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxAcquisition, 0, 0, 1, 1)

        self.retranslateUi(streamWidget)
        self.comboBoxV4l.setCurrentIndex(0)
        self.comboBoxInputNum.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBoxAudioSamplerate, QtCore.SIGNAL("toggled(bool)"), self.spinBoxAudioSamplerate.setEnabled)
        QtCore.QObject.connect(self.checkBoxAudioBitrate, QtCore.SIGNAL("toggled(bool)"), self.spinBoxAudioBitrate.setEnabled)
        QtCore.QObject.connect(self.checkBoxVideoBitrate, QtCore.SIGNAL("toggled(bool)"), self.spinBoxVideoBitrate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(streamWidget)

    def retranslateUi(self, streamWidget):
        streamWidget.setWindowTitle(QtGui.QApplication.translate("streamWidget", "Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("streamWidget", "Streaming quality", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVideoBitrate.setText(QtGui.QApplication.translate("streamWidget", "VideoBitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxVideoBitrate.setSuffix(QtGui.QApplication.translate("streamWidget", "Kbit", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAudioBitrate.setText(QtGui.QApplication.translate("streamWidget", "AudioBitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxAudioBitrate.setSuffix(QtGui.QApplication.translate("streamWidget", "Kbit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAcquisition.setTitle(QtGui.QApplication.translate("streamWidget", "Acquisition system", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("streamWidget", "Video For Linux Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxV4l.setItemText(0, QtGui.QApplication.translate("streamWidget", "v4l2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxV4l.setItemText(1, QtGui.QApplication.translate("streamWidget", "v4l", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("streamWidget", "Device Video", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("streamWidget", "Device Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAudioSamplerate.setText(QtGui.QApplication.translate("streamWidget", "AudioSamplerate", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxAudioSamplerate.setSuffix(QtGui.QApplication.translate("streamWidget", "KHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("streamWidget", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInputNum.setItemText(1, QtGui.QApplication.translate("streamWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInputNum.setItemText(2, QtGui.QApplication.translate("streamWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInputNum.setItemText(3, QtGui.QApplication.translate("streamWidget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInputNum.setItemText(4, QtGui.QApplication.translate("streamWidget", "3", None, QtGui.QApplication.UnicodeUTF8))

import stream_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    streamWidget = QtGui.QWidget()
    ui = Ui_streamWidget()
    ui.setupUi(streamWidget)
    streamWidget.show()
    sys.exit(app.exec_())

