# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcello/Documenti/sacks/sacksSvnUser/stream/user.ui'
#
# Created: Sat Mar  6 13:28:53 2010
#      by: PyQt5 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(218, 243)
        User.setMinimumSize(QtCore.QSize(0, 0))
        User.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_2 = QtGui.QGridLayout(User)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonActiveMedia = QtGui.QPushButton(User)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonActiveMedia.setFont(font)
        self.pushButtonActiveMedia.setCheckable(True)
        self.pushButtonActiveMedia.setObjectName("pushButtonActiveMedia")
        self.gridLayout.addWidget(self.pushButtonActiveMedia, 0, 0, 1, 1)
        self.pushButtonToken = QtGui.QPushButton(User)
        self.pushButtonToken.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonToken.setFont(font)
        self.pushButtonToken.setCheckable(True)
        self.pushButtonToken.setObjectName("pushButtonToken")
        self.gridLayout.addWidget(self.pushButtonToken, 0, 1, 1, 1)
        self.pushButtonRemoteDesktopControl = QtGui.QPushButton(User)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonRemoteDesktopControl.setFont(font)
        self.pushButtonRemoteDesktopControl.setCheckable(True)
        self.pushButtonRemoteDesktopControl.setObjectName("pushButtonRemoteDesktopControl")
        self.gridLayout.addWidget(self.pushButtonRemoteDesktopControl, 1, 0, 1, 1)
        self.pushButtonVoipCall = QtGui.QPushButton(User)
        self.pushButtonVoipCall.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonVoipCall.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stream/interface/images/voip/call-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVoipCall.setIcon(icon)
        self.pushButtonVoipCall.setObjectName("pushButtonVoipCall")
        self.gridLayout.addWidget(self.pushButtonVoipCall, 1, 1, 1, 1)
        self.showMedia = QtGui.QRadioButton(User)
        self.showMedia.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.showMedia.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/stream/interface/images/devices/tv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showMedia.setIcon(icon1)
        self.showMedia.setAutoExclusive(False)
        self.showMedia.setObjectName("showMedia")
        self.gridLayout.addWidget(self.showMedia, 2, 0, 1, 1)
        self.buttonOnFocus = QtGui.QRadioButton(User)
        self.buttonOnFocus.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonOnFocus.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/stream/interface/images/actions/search_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOnFocus.setIcon(icon2)
        self.buttonOnFocus.setChecked(False)
        self.buttonOnFocus.setAutoExclusive(False)
        self.buttonOnFocus.setObjectName("buttonOnFocus")
        self.gridLayout.addWidget(self.buttonOnFocus, 2, 1, 1, 1)
        self.buttonRemoteDesktop = QtGui.QRadioButton(User)
        self.buttonRemoteDesktop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonRemoteDesktop.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/stream/interface/images/apps/desktop-mdk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRemoteDesktop.setIcon(icon3)
        self.buttonRemoteDesktop.setObjectName("buttonRemoteDesktop")
        self.gridLayout.addWidget(self.buttonRemoteDesktop, 3, 0, 1, 1)
        self.labelOnline = QtGui.QLabel(User)
        self.labelOnline.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelOnline.setPixmap(QtGui.QPixmap(":/stream/images/actions/connect_no.png"))
        self.labelOnline.setScaledContents(True)
        self.labelOnline.setObjectName("labelOnline")
        self.gridLayout.addWidget(self.labelOnline, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliderVolume = QtGui.QSlider(User)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderVolume.sizePolicy().hasHeightForWidth())
        self.sliderVolume.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliderVolume.setFont(font)
        self.sliderVolume.setProperty("value", QtCore.QVariant(99))
        self.sliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolume.setInvertedAppearance(False)
        self.sliderVolume.setInvertedControls(False)
        self.sliderVolume.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderVolume.setObjectName("sliderVolume")
        self.horizontalLayout.addWidget(self.sliderVolume)
        self.labelVolume = QtGui.QLabel(User)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelVolume.setFont(font)
        self.labelVolume.setObjectName("labelVolume")
        self.horizontalLayout.addWidget(self.labelVolume)
        self.muteFlag = QtGui.QRadioButton(User)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.muteFlag.setFont(font)
        self.muteFlag.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/stream/interface/images/apps/kcmsound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteFlag.setIcon(icon4)
        self.muteFlag.setCheckable(True)
        self.muteFlag.setChecked(False)
        self.muteFlag.setAutoRepeat(False)
        self.muteFlag.setAutoExclusive(False)
        self.muteFlag.setObjectName("muteFlag")
        self.horizontalLayout.addWidget(self.muteFlag)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.lineEditSendMsg = QtGui.QLineEdit(User)
        self.lineEditSendMsg.setObjectName("lineEditSendMsg")
        self.gridLayout_2.addWidget(self.lineEditSendMsg, 2, 0, 1, 1)
        self.listWidgetReceiveMsg = QtGui.QListWidget(User)
        self.listWidgetReceiveMsg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listWidgetReceiveMsg.setFont(font)
        self.listWidgetReceiveMsg.setObjectName("listWidgetReceiveMsg")
        self.gridLayout_2.addWidget(self.listWidgetReceiveMsg, 3, 0, 1, 1)

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        User.setWindowTitle(QtGui.QApplication.translate("User", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonActiveMedia.setToolTip(QtGui.QApplication.translate("User", "Abilitate media send", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonActiveMedia.setText(QtGui.QApplication.translate("User", "Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonToken.setToolTip(QtGui.QApplication.translate("User", "Give turn to user", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonToken.setText(QtGui.QApplication.translate("User", "Token", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemoteDesktopControl.setText(QtGui.QApplication.translate("User", "DeskCtrl", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonVoipCall.setToolTip(QtGui.QApplication.translate("User", "Voip Call", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonVoipCall.setText(QtGui.QApplication.translate("User", "Call", None, QtGui.QApplication.UnicodeUTF8))
        self.showMedia.setText(QtGui.QApplication.translate("User", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOnFocus.setText(QtGui.QApplication.translate("User", "On Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemoteDesktop.setText(QtGui.QApplication.translate("User", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVolume.setText(QtGui.QApplication.translate("User", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.muteFlag.setText(QtGui.QApplication.translate("User", "Mute", None, QtGui.QApplication.UnicodeUTF8))

from . import stream_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    User = QtGui.QWidget()
    ui = Ui_User()
    ui.setupUi(User)
    User.show()
    sys.exit(app.exec_())

