# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcello/Documenti/sacks/sacksSvnUser/interface/mainwindow.ui'
#
# Created: Sat Mar  6 13:06:39 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/kontact_contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuWindows = QtGui.QMenu(self.menuBar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuAction = QtGui.QMenu(self.menuBar)
        self.menuAction.setObjectName("menuAction")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetRoom = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetRoom.sizePolicy().hasHeightForWidth())
        self.dockWidgetRoom.setSizePolicy(sizePolicy)
        self.dockWidgetRoom.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetRoom.setObjectName("dockWidgetRoom")
        self.dockWidgeRoomContents = QtGui.QWidget()
        self.dockWidgeRoomContents.setObjectName("dockWidgeRoomContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgeRoomContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditRoomMsg = QtGui.QLineEdit(self.dockWidgeRoomContents)
        self.lineEditRoomMsg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRoomMsg.sizePolicy().hasHeightForWidth())
        self.lineEditRoomMsg.setSizePolicy(sizePolicy)
        self.lineEditRoomMsg.setObjectName("lineEditRoomMsg")
        self.horizontalLayout.addWidget(self.lineEditRoomMsg)
        self.labelLinkToServer = QtGui.QLabel(self.dockWidgeRoomContents)
        self.labelLinkToServer.setMinimumSize(QtCore.QSize(17, 17))
        self.labelLinkToServer.setMaximumSize(QtCore.QSize(17, 17))
        self.labelLinkToServer.setScaledContents(True)
        self.labelLinkToServer.setObjectName("labelLinkToServer")
        self.horizontalLayout.addWidget(self.labelLinkToServer)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidgetRoomBox = QtGui.QListWidget(self.dockWidgeRoomContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetRoomBox.sizePolicy().hasHeightForWidth())
        self.listWidgetRoomBox.setSizePolicy(sizePolicy)
        self.listWidgetRoomBox.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetRoomBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listWidgetRoomBox.setFont(font)
        self.listWidgetRoomBox.setFrameShadow(QtGui.QFrame.Plain)
        self.listWidgetRoomBox.setAutoScroll(False)
        self.listWidgetRoomBox.setFlow(QtGui.QListView.TopToBottom)
        self.listWidgetRoomBox.setProperty("isWrapping", QtCore.QVariant(False))
        self.listWidgetRoomBox.setLayoutMode(QtGui.QListView.SinglePass)
        self.listWidgetRoomBox.setObjectName("listWidgetRoomBox")
        self.verticalLayout_2.addWidget(self.listWidgetRoomBox)
        self.dockWidgetRoom.setWidget(self.dockWidgeRoomContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetRoom)
        self.dockWidgetMediaFocus = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetMediaFocus.sizePolicy().hasHeightForWidth())
        self.dockWidgetMediaFocus.setSizePolicy(sizePolicy)
        self.dockWidgetMediaFocus.setObjectName("dockWidgetMediaFocus")
        self.dockWidgetFocusContents = QtGui.QWidget()
        self.dockWidgetFocusContents.setObjectName("dockWidgetFocusContents")
        self.verticalLayoutFocus = QtGui.QVBoxLayout(self.dockWidgetFocusContents)
        self.verticalLayoutFocus.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayoutFocus.setObjectName("verticalLayoutFocus")
        self.dockWidgetMediaFocus.setWidget(self.dockWidgetFocusContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetMediaFocus)
        self.dockWidgetUser = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetUser.sizePolicy().hasHeightForWidth())
        self.dockWidgetUser.setSizePolicy(sizePolicy)
        self.dockWidgetUser.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetUser.setObjectName("dockWidgetUser")
        self.dockWidgetUserContents = QtGui.QWidget()
        self.dockWidgetUserContents.setObjectName("dockWidgetUserContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetUserContents)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtGui.QToolBox(self.dockWidgetUserContents)
        self.toolBox.setMinimumSize(QtCore.QSize(260, 240))
        self.toolBox.setObjectName("toolBox")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.dockWidgetUser.setWidget(self.dockWidgetUserContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetUser)
        self.dockWidgetVoip = QtGui.QDockWidget(MainWindow)
        self.dockWidgetVoip.setObjectName("dockWidgetVoip")
        self.dockWidgetVoipContents = QtGui.QWidget()
        self.dockWidgetVoipContents.setObjectName("dockWidgetVoipContents")
        self.layoutVoip = QtGui.QVBoxLayout(self.dockWidgetVoipContents)
        self.layoutVoip.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.layoutVoip.setObjectName("layoutVoip")
        self.dockWidgetVoip.setWidget(self.dockWidgetVoipContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetVoip)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/images/filequit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setCheckable(False)
        self.actionNew.setChecked(False)
        self.actionNew.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/images/editadd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setAutoRepeat(True)
        self.actionNew.setMenuRole(QtGui.QAction.QuitRole)
        self.actionNew.setObjectName("actionNew")
        self.actionTile = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/view_left_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTile.setIcon(icon3)
        self.actionTile.setObjectName("actionTile")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/prefix1/images/editdelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon4)
        self.actionDelete.setObjectName("actionDelete")
        self.actionCascade = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/prefix1/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCascade.setIcon(icon5)
        self.actionCascade.setObjectName("actionCascade")
        self.actionSendVideo = QtGui.QAction(MainWindow)
        self.actionSendVideo.setCheckable(True)
        self.actionSendVideo.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/webcamsend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendVideo.setIcon(icon6)
        self.actionSendVideo.setObjectName("actionSendVideo")
        self.actionVideoStream = QtGui.QAction(MainWindow)
        self.actionVideoStream.setCheckable(True)
        self.actionVideoStream.setChecked(False)
        self.actionVideoStream.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/prefix1/images/devices/tv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVideoStream.setIcon(icon7)
        self.actionVideoStream.setObjectName("actionVideoStream")
        self.actionConnection = QtGui.QAction(MainWindow)
        self.actionConnection.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/connect_no.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/connect_creating.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionConnection.setIcon(icon8)
        self.actionConnection.setObjectName("actionConnection")
        self.actionSendDesktop = QtGui.QAction(MainWindow)
        self.actionSendDesktop.setCheckable(True)
        self.actionSendDesktop.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/new/prefix1/images/filesystems/network_local.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendDesktop.setIcon(icon9)
        self.actionSendDesktop.setObjectName("actionSendDesktop")
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigure.setIcon(icon10)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionShowDockPanels = QtGui.QAction(MainWindow)
        self.actionShowDockPanels.setCheckable(True)
        self.actionShowDockPanels.setChecked(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/show_side_panel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowDockPanels.setIcon(icon11)
        self.actionShowDockPanels.setObjectName("actionShowDockPanels")
        self.actionFocusRequest = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/new/prefix1/images/actions/token.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFocusRequest.setIcon(icon12)
        self.actionFocusRequest.setObjectName("actionFocusRequest")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/new/prefix2/images/actions/messagebox_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon13)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionDelete)
        self.menu_File.addAction(self.actionExit)
        self.menuWindows.addAction(self.actionTile)
        self.menuWindows.addAction(self.actionCascade)
        self.menuAction.addAction(self.actionConnection)
        self.menuAction.addAction(self.actionSendVideo)
        self.menuAction.addAction(self.actionSendDesktop)
        self.menuAction.addAction(self.actionVideoStream)
        self.menuAction.addAction(self.actionFocusRequest)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionConfigure)
        self.menuAction.addAction(self.actionShowDockPanels)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTile)
        self.toolBar.addAction(self.actionCascade)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnection)
        self.toolBar.addAction(self.actionSendVideo)
        self.toolBar.addAction(self.actionSendDesktop)
        self.toolBar.addAction(self.actionVideoStream)
        self.toolBar.addAction(self.actionFocusRequest)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConfigure)
        self.toolBar.addAction(self.actionShowDockPanels)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionShowDockPanels, QtCore.SIGNAL("toggled(bool)"), self.dockWidgetRoom.setVisible)
        QtCore.QObject.connect(self.actionShowDockPanels, QtCore.SIGNAL("toggled(bool)"), self.dockWidgetUser.setVisible)
        QtCore.QObject.connect(self.actionShowDockPanels, QtCore.SIGNAL("toggled(bool)"), self.dockWidgetVoip.setVisible)
        QtCore.QObject.connect(self.actionShowDockPanels, QtCore.SIGNAL("toggled(bool)"), self.dockWidgetMediaFocus.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sacks", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("MainWindow", "&Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "Actio&n", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetRoom.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&Group", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMediaFocus.setWindowTitle(QtGui.QApplication.translate("MainWindow", "On Focus:", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetUser.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&Utenti", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetVoip.setWindowTitle(QtGui.QApplication.translate("MainWindow", "&Voip", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTile.setText(QtGui.QApplication.translate("MainWindow", "&Tile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCascade.setText(QtGui.QApplication.translate("MainWindow", "Cascade", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSendVideo.setText(QtGui.QApplication.translate("MainWindow", "SendVideo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVideoStream.setText(QtGui.QApplication.translate("MainWindow", "Show Video Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnection.setText(QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSendDesktop.setText(QtGui.QApplication.translate("MainWindow", "sendDesktop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDockPanels.setText(QtGui.QApplication.translate("MainWindow", "Show Dock Panels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDockPanels.setToolTip(QtGui.QApplication.translate("MainWindow", "Show side panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDockPanels.setShortcut(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFocusRequest.setText(QtGui.QApplication.translate("MainWindow", "Focus Request", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About Sacks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setToolTip(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

