# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcello/Documenti/sacks/sacksSvnUser/voip/voipInterface.ui'
#
# Created: Mon Dec 21 14:15:55 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VoipInterface(object):
    def setupUi(self, VoipInterface):
        VoipInterface.setObjectName("VoipInterface")
        VoipInterface.resize(220, 277)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VoipInterface.sizePolicy().hasHeightForWidth())
        VoipInterface.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(VoipInterface)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelVoipInfo = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVoipInfo.sizePolicy().hasHeightForWidth())
        self.labelVoipInfo.setSizePolicy(sizePolicy)
        self.labelVoipInfo.setObjectName("labelVoipInfo")
        self.verticalLayout.addWidget(self.labelVoipInfo)
        self.labelVoipDisplay = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVoipDisplay.sizePolicy().hasHeightForWidth())
        self.labelVoipDisplay.setSizePolicy(sizePolicy)
        self.labelVoipDisplay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 148, 152))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 148, 152))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 148, 152))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 111, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 222, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.labelVoipDisplay.setPalette(palette)
        self.labelVoipDisplay.setAutoFillBackground(True)
        self.labelVoipDisplay.setLineWidth(1)
        self.labelVoipDisplay.setScaledContents(True)
        self.labelVoipDisplay.setWordWrap(False)
        self.labelVoipDisplay.setIndent(-1)
        self.labelVoipDisplay.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelVoipDisplay.setObjectName("labelVoipDisplay")
        self.verticalLayout.addWidget(self.labelVoipDisplay)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayoutKeys = QtGui.QGridLayout()
        self.gridLayoutKeys.setObjectName("gridLayoutKeys")
        self.pushButtonKey1 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey1.sizePolicy().hasHeightForWidth())
        self.pushButtonKey1.setSizePolicy(sizePolicy)
        self.pushButtonKey1.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey1.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey1.setObjectName("pushButtonKey1")
        self.gridLayoutKeys.addWidget(self.pushButtonKey1, 0, 0, 1, 1)
        self.pushButtonKey2 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey2.sizePolicy().hasHeightForWidth())
        self.pushButtonKey2.setSizePolicy(sizePolicy)
        self.pushButtonKey2.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey2.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey2.setObjectName("pushButtonKey2")
        self.gridLayoutKeys.addWidget(self.pushButtonKey2, 0, 1, 1, 1)
        self.pushButtonKey3 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey3.sizePolicy().hasHeightForWidth())
        self.pushButtonKey3.setSizePolicy(sizePolicy)
        self.pushButtonKey3.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey3.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey3.setObjectName("pushButtonKey3")
        self.gridLayoutKeys.addWidget(self.pushButtonKey3, 0, 2, 1, 1)
        self.pushButtonKey4 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey4.sizePolicy().hasHeightForWidth())
        self.pushButtonKey4.setSizePolicy(sizePolicy)
        self.pushButtonKey4.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey4.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey4.setObjectName("pushButtonKey4")
        self.gridLayoutKeys.addWidget(self.pushButtonKey4, 1, 0, 1, 1)
        self.pushButtonKey5 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey5.sizePolicy().hasHeightForWidth())
        self.pushButtonKey5.setSizePolicy(sizePolicy)
        self.pushButtonKey5.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey5.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey5.setObjectName("pushButtonKey5")
        self.gridLayoutKeys.addWidget(self.pushButtonKey5, 1, 1, 1, 1)
        self.pushButtonKey6 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey6.sizePolicy().hasHeightForWidth())
        self.pushButtonKey6.setSizePolicy(sizePolicy)
        self.pushButtonKey6.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey6.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey6.setObjectName("pushButtonKey6")
        self.gridLayoutKeys.addWidget(self.pushButtonKey6, 1, 2, 1, 1)
        self.pushButtonKey7 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey7.sizePolicy().hasHeightForWidth())
        self.pushButtonKey7.setSizePolicy(sizePolicy)
        self.pushButtonKey7.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey7.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey7.setObjectName("pushButtonKey7")
        self.gridLayoutKeys.addWidget(self.pushButtonKey7, 2, 0, 1, 1)
        self.pushButtonKey8 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey8.sizePolicy().hasHeightForWidth())
        self.pushButtonKey8.setSizePolicy(sizePolicy)
        self.pushButtonKey8.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey8.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey8.setObjectName("pushButtonKey8")
        self.gridLayoutKeys.addWidget(self.pushButtonKey8, 2, 1, 1, 1)
        self.pushButtonKey9 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey9.sizePolicy().hasHeightForWidth())
        self.pushButtonKey9.setSizePolicy(sizePolicy)
        self.pushButtonKey9.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey9.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKey9.setObjectName("pushButtonKey9")
        self.gridLayoutKeys.addWidget(self.pushButtonKey9, 2, 2, 1, 1)
        self.pushButtonKeyAsterisk = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKeyAsterisk.sizePolicy().hasHeightForWidth())
        self.pushButtonKeyAsterisk.setSizePolicy(sizePolicy)
        self.pushButtonKeyAsterisk.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKeyAsterisk.setMaximumSize(QtCore.QSize(64, 16777215))
        self.pushButtonKeyAsterisk.setObjectName("pushButtonKeyAsterisk")
        self.gridLayoutKeys.addWidget(self.pushButtonKeyAsterisk, 3, 0, 1, 1)
        self.pushButtonKey0 = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKey0.sizePolicy().hasHeightForWidth())
        self.pushButtonKey0.setSizePolicy(sizePolicy)
        self.pushButtonKey0.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKey0.setMaximumSize(QtCore.QSize(64, 16777215))
        self.pushButtonKey0.setObjectName("pushButtonKey0")
        self.gridLayoutKeys.addWidget(self.pushButtonKey0, 3, 1, 1, 1)
        self.pushButtonKeyCancel = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonKeyCancel.sizePolicy().hasHeightForWidth())
        self.pushButtonKeyCancel.setSizePolicy(sizePolicy)
        self.pushButtonKeyCancel.setMinimumSize(QtCore.QSize(64, 27))
        self.pushButtonKeyCancel.setMaximumSize(QtCore.QSize(64, 27))
        self.pushButtonKeyCancel.setObjectName("pushButtonKeyCancel")
        self.gridLayoutKeys.addWidget(self.pushButtonKeyCancel, 3, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayoutKeys)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCall = QtGui.QPushButton(self.centralWidget)
        self.pushButtonCall.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCall.sizePolicy().hasHeightForWidth())
        self.pushButtonCall.setSizePolicy(sizePolicy)
        self.pushButtonCall.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonCall.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonCall.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/call-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCall.setIcon(icon)
        self.pushButtonCall.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonCall.setObjectName("pushButtonCall")
        self.horizontalLayout.addWidget(self.pushButtonCall)
        self.pushButtonHangup = QtGui.QPushButton(self.centralWidget)
        self.pushButtonHangup.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonHangup.sizePolicy().hasHeightForWidth())
        self.pushButtonHangup.setSizePolicy(sizePolicy)
        self.pushButtonHangup.setMinimumSize(QtCore.QSize(100, 27))
        self.pushButtonHangup.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonHangup.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/call-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHangup.setIcon(icon1)
        self.pushButtonHangup.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonHangup.setObjectName("pushButtonHangup")
        self.horizontalLayout.addWidget(self.pushButtonHangup)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.comboBoxVoipUrls = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxVoipUrls.sizePolicy().hasHeightForWidth())
        self.comboBoxVoipUrls.setSizePolicy(sizePolicy)
        self.comboBoxVoipUrls.setEditable(True)
        self.comboBoxVoipUrls.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.comboBoxVoipUrls.setObjectName("comboBoxVoipUrls")
        self.verticalLayout_2.addWidget(self.comboBoxVoipUrls)
        VoipInterface.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(VoipInterface)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 220, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuVoip = QtGui.QMenu(self.menuBar)
        self.menuVoip.setObjectName("menuVoip")
        VoipInterface.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(VoipInterface)
        self.toolBar.setObjectName("toolBar")
        VoipInterface.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRegister = QtGui.QAction(VoipInterface)
        self.actionRegister.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/internet-telephony_notOnline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/internet-telephony_connecting.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRegister.setIcon(icon2)
        self.actionRegister.setObjectName("actionRegister")
        self.actionConfigure = QtGui.QAction(VoipInterface)
        self.actionConfigure.setCheckable(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/configure_voip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigure.setIcon(icon3)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionCall = QtGui.QAction(VoipInterface)
        self.actionCall.setIcon(icon)
        self.actionCall.setObjectName("actionCall")
        self.actionHangup = QtGui.QAction(VoipInterface)
        self.actionHangup.setIcon(icon1)
        self.actionHangup.setObjectName("actionHangup")
        self.actionAbout = QtGui.QAction(VoipInterface)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/voip/interface/images/voip/messagebox_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.menuVoip.addAction(self.actionRegister)
        self.menuVoip.addAction(self.actionCall)
        self.menuVoip.addAction(self.actionHangup)
        self.menuVoip.addAction(self.actionConfigure)
        self.menuVoip.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuVoip.menuAction())
        self.toolBar.addAction(self.actionRegister)
        self.toolBar.addAction(self.actionCall)
        self.toolBar.addAction(self.actionHangup)

        self.retranslateUi(VoipInterface)
        QtCore.QObject.connect(self.actionCall, QtCore.SIGNAL("triggered()"), self.pushButtonCall.animateClick)
        QtCore.QObject.connect(self.actionHangup, QtCore.SIGNAL("triggered()"), self.pushButtonHangup.animateClick)
        QtCore.QMetaObject.connectSlotsByName(VoipInterface)

    def retranslateUi(self, VoipInterface):
        VoipInterface.setWindowTitle(QtGui.QApplication.translate("VoipInterface", "VoipInterface", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey1.setText(QtGui.QApplication.translate("VoipInterface", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey2.setText(QtGui.QApplication.translate("VoipInterface", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey3.setText(QtGui.QApplication.translate("VoipInterface", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey4.setText(QtGui.QApplication.translate("VoipInterface", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey5.setText(QtGui.QApplication.translate("VoipInterface", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey6.setText(QtGui.QApplication.translate("VoipInterface", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey7.setText(QtGui.QApplication.translate("VoipInterface", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey8.setText(QtGui.QApplication.translate("VoipInterface", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey9.setText(QtGui.QApplication.translate("VoipInterface", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKeyAsterisk.setText(QtGui.QApplication.translate("VoipInterface", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKey0.setText(QtGui.QApplication.translate("VoipInterface", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonKeyCancel.setText(QtGui.QApplication.translate("VoipInterface", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCall.setText(QtGui.QApplication.translate("VoipInterface", "&Call", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHangup.setText(QtGui.QApplication.translate("VoipInterface", "Hangup", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVoip.setTitle(QtGui.QApplication.translate("VoipInterface", "Voip", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("VoipInterface", "Voip ToolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegister.setText(QtGui.QApplication.translate("VoipInterface", "Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("VoipInterface", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setToolTip(QtGui.QApplication.translate("VoipInterface", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCall.setText(QtGui.QApplication.translate("VoipInterface", "Call", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHangup.setText(QtGui.QApplication.translate("VoipInterface", "Hangup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("VoipInterface", "About", None, QtGui.QApplication.UnicodeUTF8))

import voip_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    VoipInterface = QtGui.QMainWindow()
    ui = Ui_VoipInterface()
    ui.setupUi(VoipInterface)
    VoipInterface.show()
    sys.exit(app.exec_())

